### ISSUE TITLE
Packages: qt5-websockets and qt5-remoteobjects not found

### ISSUE THREAD

**Issue by ServusNL** [tprelog/iocage-ozwdaemon#1]
I'm following the guide but I am not able to install the following dependencies:

qt5-websockets and qt5-remoteobjects 

```
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'qt5-remoteobjects' have been found in the repositories
pkg: No packages available to install matching 'qt5-websockets' have been foundin the repositories
```

**Comment by tprelog** [comment]
Hi @ServusNL -- Sorry I have not tested this since upgrading to TrueNAS CORE. (I've been using Docker more these days) It looks those packages are no longer available in any FreeBSD 11.X releases so this will no longer work if your still using FreeNAS. (You can not make a Jail using a new version, than what the host is running)

If you have upgrade to TrueNAS CORE, simply create the jail using either the `12.1-RELEASE` or `12.2-RELEASE` instead.

I have updated the jail creation step in the wiki to use the `12.2-RELEASE`, matching the release currently used by the plugins.

**Comment by ServusNL** [comment]
Thanks! Currently I'm also running my HA in docker but I'm looking for a way to use my Z-wave stick. I understand that making the USB-stick available in the virtual machine (hosting my docker containers) is near to impossible. 

Anyway. This issue can be closed. Thanks again!

**Comment by tprelog** [comment]
I'm currently looking at TrueNAS SCALE (will be released later this year, based on Debian Linux not FreeBSD), which will support both running Docker containers and proper pass-through for devices to a VM

**Comment by tprelog** [comment]
Just FYI, the ozwdaemon developer is taking some off:
https://community.home-assistant.io/t/can-we-revisit-the-move-to-qt-openzwave/262612/140?u=troy

Z-Wave is now changing directions once again in Home Assistant:
https://github.com/home-assistant/architecture/issues/483

**Comment by ServusNL** [comment]
> I'm currently looking at TrueNAS SCALE (will be released later this year, based on Debian Linux not FreeBSD), which will support both running Docker containers and proper pass-through for devices to a VM

Thanks for the information. Will wait for TrueNAS SCALE production release with automated migration from CORE then :) Before saying goodbye to my Fibaro Homecenter II. Hopefully they are still on track for a Q1 release. Then I will finally be able to remove an unnecessary VM layer for my Docker containers and it looks like binding the UZB stick will be a breeze.
